-- Query para crear la tabla respuesta_pregunta y para crear cada una de las respuestas que va a tener cada pregunta
-- Sentencia para crear la tabla respuesta_pregunta  la cual va a estar asociada a la tabla preguntas por medio del id de cada pregunta.
CREATE TABLE respuesta_preguntas(
    id serial PRIMARY KEY,
    pregunta_id int REFERENCES preguntas(id) ON DELETE CASCADE, -- Relación con la tabla preguntas
    opcion varchar(255), -- Texto de la opción de respuesta
    es_correcta boolean NOT NULL DEFAULT FALSE, -- Indica si esta opción es la correcta
    created_at timestamp DEFAULT NOW(),
    updated_at timestamp DEFAULT NOW()
);

-- Sentencia para crear cada una de las respuestas asociadas a una pregunta de la parte 1 (imagenes)
INSERT INTO respuesta_preguntas(pregunta_id, opcion, es_correcta)
    VALUES (1, 'parte-1-pregunta-1-opcion-1-imagen-A', TRUE),
(1, 'parte-1-pregunta-1-opcion-1-imagen-B', FALSE),
(1, 'parte-1-pregunta-1-opcion-1-imagen-C', FALSE),
(2, 'parte-1-pregunta-1-opcion-2-imagen-A', TRUE),
(2, 'parte-1-pregunta-1-opcion-2-imagen-B', FALSE),
(2, 'parte-1-pregunta-1-opcion-2-imagen-C', FALSE),
(3, 'parte-1-pregunta-1-opcion-3-imagen-A', TRUE),
(3, 'parte-1-pregunta-1-opcion-3-imagen-B', FALSE),
(3, 'parte-1-pregunta-1-opcion-3-imagen-C', FALSE),
(4, 'parte-1-pregunta-1-opcion-4-imagen-A', TRUE),
(4, 'parte-1-pregunta-1-opcion-4-imagen-B', FALSE),
(4, 'parte-1-pregunta-1-opcion-4-imagen-C', FALSE),
(5, 'parte-1-pregunta-1-opcion-5-imagen-A', TRUE),
(5, 'parte-1-pregunta-1-opcion-5-imagen-B', FALSE),
(5, 'parte-1-pregunta-1-opcion-5-imagen-C', FALSE),
(6, 'parte-1-pregunta-2-opcion-1-imagen-A', TRUE),
(6, 'parte-1-pregunta-2-opcion-1-imagen-B', FALSE),
(6, 'parte-1-pregunta-2-opcion-1-imagen-C', FALSE),
(7, 'parte-1-pregunta-2-opcion-2-imagen-A', TRUE),
(7, 'parte-1-pregunta-2-opcion-2-imagen-B', FALSE),
(7, 'parte-1-pregunta-2-opcion-2-imagen-C', FALSE),
(8, 'parte-1-pregunta-2-opcion-3-imagen-A', TRUE),
(8, 'parte-1-pregunta-2-opcion-3-imagen-B', FALSE),
(8, 'parte-1-pregunta-2-opcion-3-imagen-C', FALSE),
(9, 'parte-1-pregunta-2-opcion-4-imagen-A', TRUE),
(9, 'parte-1-pregunta-2-opcion-4-imagen-B', FALSE),
(9, 'parte-1-pregunta-2-opcion-4-imagen-C', FALSE),
(10, 'parte-1-pregunta-2-opcion-5-imagen-A', TRUE),
(10, 'parte-1-pregunta-2-opcion-5-imagen-B', FALSE),
(10, 'parte-1-pregunta-2-opcion-5-imagen-C', FALSE),
(11, 'parte-1-pregunta-3-opcion-1-imagen-A', TRUE),
(11, 'parte-1-pregunta-3-opcion-1-imagen-B', FALSE),
(11, 'parte-1-pregunta-3-opcion-1-imagen-C', FALSE),
(12, 'parte-1-pregunta-3-opcion-2-imagen-A', TRUE),
(12, 'parte-1-pregunta-3-opcion-2-imagen-B', FALSE),
(12, 'parte-1-pregunta-3-opcion-2-imagen-C', FALSE),
(13, 'parte-1-pregunta-3-opcion-3-imagen-A', TRUE),
(13, 'parte-1-pregunta-3-opcion-3-imagen-B', FALSE),
(13, 'parte-1-pregunta-3-opcion-3-imagen-C', FALSE),
(14, 'parte-1-pregunta-3-opcion-4-imagen-A', TRUE),
(14, 'parte-1-pregunta-3-opcion-4-imagen-B', FALSE),
(14, 'parte-1-pregunta-3-opcion-4-imagen-C', FALSE),
(15, 'parte-1-pregunta-3-opcion-5-imagen-A', TRUE),
(15, 'parte-1-pregunta-3-opcion-5-imagen-B', FALSE),
(15, 'parte-1-pregunta-3-opcion-5-imagen-C', FALSE),
(16, 'parte-1-pregunta-4-opcion-1-imagen-A', TRUE),
(16, 'parte-1-pregunta-4-opcion-1-imagen-B', FALSE),
(16, 'parte-1-pregunta-4-opcion-1-imagen-C', FALSE),
(17, 'parte-1-pregunta-4-opcion-2-imagen-A', TRUE),
(17, 'parte-1-pregunta-4-opcion-2-imagen-B', FALSE),
(17, 'parte-1-pregunta-4-opcion-2-imagen-C', FALSE),
(18, 'parte-1-pregunta-4-opcion-3-imagen-A', TRUE),
(18, 'parte-1-pregunta-4-opcion-3-imagen-B', FALSE),
(18, 'parte-1-pregunta-4-opcion-3-imagen-C', FALSE),
(19, 'parte-1-pregunta-4-opcion-4-imagen-A', TRUE),
(19, 'parte-1-pregunta-4-opcion-4-imagen-B', FALSE),
(19, 'parte-1-pregunta-4-opcion-4-imagen-C', FALSE),
(20, 'parte-1-pregunta-4-opcion-5-imagen-A', TRUE),
(20, 'parte-1-pregunta-4-opcion-5-imagen-B', FALSE),
(20, 'parte-1-pregunta-4-opcion-5-imagen-C', FALSE),
(21, 'parte-1-pregunta-5-opcion-1-imagen-A', TRUE),
(21, 'parte-1-pregunta-5-opcion-1-imagen-B', FALSE),
(21, 'parte-1-pregunta-5-opcion-1-imagen-C', FALSE),
(22, 'parte-1-pregunta-5-opcion-2-imagen-A', TRUE),
(22, 'parte-1-pregunta-5-opcion-2-imagen-B', FALSE),
(22, 'parte-1-pregunta-5-opcion-2-imagen-C', FALSE),
(23, 'parte-1-pregunta-5-opcion-3-imagen-A', TRUE),
(23, 'parte-1-pregunta-5-opcion-3-imagen-B', FALSE),
(23, 'parte-1-pregunta-5-opcion-3-imagen-C', FALSE),
(24, 'parte-1-pregunta-5-opcion-4-imagen-A', TRUE),
(24, 'parte-1-pregunta-5-opcion-4-imagen-B', FALSE),
(24, 'parte-1-pregunta-5-opcion-4-imagen-C', FALSE),
(25, 'parte-1-pregunta-5-opcion-5-imagen-A', TRUE),
(25, 'parte-1-pregunta-5-opcion-5-imagen-B', FALSE),
(25, 'parte-1-pregunta-5-opcion-5-imagen-C', FALSE);

-- Sentencia para crear cada una de las respuestas asociadas a una pregunta de la parte 2 (texto)
INSERT INTO respuesta_preguntas(pregunta_id, opcion, es_correcta)
    VALUES (26, 'parte-2-pregunta-1-opcion-1-texto-A', TRUE),
(26, 'parte-2-pregunta-1-opcion-1-texto-B', FALSE),
(26, 'parte-2-pregunta-1-opcion-1-texto-C', FALSE),
(27, 'parte-2-pregunta-1-opcion-2-texto-A', TRUE),
(27, 'parte-2-pregunta-1-opcion-2-texto-B', FALSE),
(27, 'parte-2-pregunta-1-opcion-2-texto-C', FALSE),
(28, 'parte-2-pregunta-1-opcion-3-texto-A', TRUE),
(28, 'parte-2-pregunta-1-opcion-3-texto-B', FALSE),
(28, 'parte-2-pregunta-1-opcion-3-texto-C', FALSE),
(29, 'parte-2-pregunta-1-opcion-4-texto-A', TRUE),
(29, 'parte-2-pregunta-1-opcion-4-texto-B', FALSE),
(29, 'parte-2-pregunta-1-opcion-4-texto-C', FALSE),
(30, 'parte-2-pregunta-1-opcion-5-texto-A', TRUE),
(30, 'parte-2-pregunta-1-opcion-5-texto-B', FALSE),
(30, 'parte-2-pregunta-1-opcion-5-texto-C', FALSE),
(31, 'parte-2-pregunta-2-opcion-1-texto-A', TRUE),
(31, 'parte-2-pregunta-2-opcion-1-texto-B', FALSE),
(31, 'parte-2-pregunta-2-opcion-1-texto-C', FALSE),
(32, 'parte-2-pregunta-2-opcion-2-texto-A', TRUE),
(32, 'parte-2-pregunta-2-opcion-2-texto-B', FALSE),
(32, 'parte-2-pregunta-2-opcion-2-texto-C', FALSE),
(33, 'parte-2-pregunta-2-opcion-3-texto-A', TRUE),
(33, 'parte-2-pregunta-2-opcion-3-texto-B', FALSE),
(33, 'parte-2-pregunta-2-opcion-3-texto-C', FALSE),
(34, 'parte-2-pregunta-2-opcion-4-texto-A', TRUE),
(34, 'parte-2-pregunta-2-opcion-4-texto-B', FALSE),
(34, 'parte-2-pregunta-2-opcion-4-texto-C', FALSE),
(35, 'parte-2-pregunta-2-opcion-5-texto-A', TRUE),
(35, 'parte-2-pregunta-2-opcion-5-texto-B', FALSE),
(35, 'parte-2-pregunta-2-opcion-5-texto-C', FALSE),
(36, 'parte-2-pregunta-3-opcion-1-texto-A', TRUE),
(36, 'parte-2-pregunta-3-opcion-1-texto-B', FALSE),
(36, 'parte-2-pregunta-3-opcion-1-texto-C', FALSE),
(37, 'parte-2-pregunta-3-opcion-2-texto-A', TRUE),
(37, 'parte-2-pregunta-3-opcion-2-texto-B', FALSE),
(37, 'parte-2-pregunta-3-opcion-2-texto-C', FALSE),
(38, 'parte-2-pregunta-3-opcion-3-texto-A', TRUE),
(38, 'parte-2-pregunta-3-opcion-3-texto-B', FALSE),
(38, 'parte-2-pregunta-3-opcion-3-texto-C', FALSE),
(39, 'parte-2-pregunta-3-opcion-4-texto-A', TRUE),
(39, 'parte-2-pregunta-3-opcion-4-texto-B', FALSE),
(39, 'parte-2-pregunta-3-opcion-4-texto-C', FALSE),
(40, 'parte-2-pregunta-3-opcion-5-texto-A', TRUE),
(40, 'parte-2-pregunta-3-opcion-5-texto-B', FALSE),
(40, 'parte-2-pregunta-3-opcion-5-texto-C', FALSE),
(41, 'parte-2-pregunta-4-opcion-1-texto-A', TRUE),
(41, 'parte-2-pregunta-4-opcion-1-texto-B', FALSE),
(41, 'parte-2-pregunta-4-opcion-1-texto-C', FALSE),
(42, 'parte-2-pregunta-4-opcion-2-texto-A', TRUE),
(42, 'parte-2-pregunta-4-opcion-2-texto-B', FALSE),
(42, 'parte-2-pregunta-4-opcion-2-texto-C', FALSE),
(43, 'parte-2-pregunta-4-opcion-3-texto-A', TRUE),
(43, 'parte-2-pregunta-4-opcion-3-texto-B', FALSE),
(43, 'parte-2-pregunta-4-opcion-3-texto-C', FALSE),
(44, 'parte-2-pregunta-4-opcion-4-texto-A', TRUE),
(44, 'parte-2-pregunta-4-opcion-4-texto-B', FALSE),
(44, 'parte-2-pregunta-4-opcion-4-texto-C', FALSE),
(45, 'parte-2-pregunta-4-opcion-5-texto-A', TRUE),
(45, 'parte-2-pregunta-4-opcion-5-texto-B', FALSE),
(45, 'parte-2-pregunta-4-opcion-5-texto-C', FALSE),
(46, 'parte-2-pregunta-5-opcion-1-texto-A', TRUE),
(46, 'parte-2-pregunta-5-opcion-1-texto-B', FALSE),
(46, 'parte-2-pregunta-5-opcion-1-texto-C', FALSE),
(47, 'parte-2-pregunta-5-opcion-2-texto-A', TRUE),
(47, 'parte-2-pregunta-5-opcion-2-texto-B', FALSE),
(47, 'parte-2-pregunta-5-opcion-2-texto-C', FALSE),
(48, 'parte-2-pregunta-5-opcion-3-texto-A', TRUE),
(48, 'parte-2-pregunta-5-opcion-3-texto-B', FALSE),
(48, 'parte-2-pregunta-5-opcion-3-texto-C', FALSE),
(49, 'parte-2-pregunta-5-opcion-4-texto-A', TRUE),
(49, 'parte-2-pregunta-5-opcion-4-texto-B', FALSE),
(49, 'parte-2-pregunta-5-opcion-4-texto-C', FALSE),
(50, 'parte-2-pregunta-5-opcion-5-texto-A', TRUE),
(50, 'parte-2-pregunta-5-opcion-5-texto-B', FALSE),
(50, 'parte-2-pregunta-5-opcion-5-texto-C', FALSE);

-- Sentencia para crear cada una de las respuestas asociadas a una pregunta de la parte 3 (texto)
INSERT INTO respuesta_preguntas(pregunta_id, opcion, es_correcta)
    VALUES (51, 'parte-3-pregunta-1-opcion-1-texto-A', TRUE),
(51, 'parte-3-pregunta-1-opcion-1-texto-B', FALSE),
(51, 'parte-3-pregunta-1-opcion-1-texto-C', FALSE),
(52, 'parte-3-pregunta-1-opcion-2-texto-A', TRUE),
(52, 'parte-3-pregunta-1-opcion-2-texto-B', FALSE),
(52, 'parte-3-pregunta-1-opcion-2-texto-C', FALSE),
(53, 'parte-3-pregunta-1-opcion-3-texto-A', TRUE),
(53, 'parte-3-pregunta-1-opcion-3-texto-B', FALSE),
(53, 'parte-3-pregunta-1-opcion-3-texto-C', FALSE),
(54, 'parte-3-pregunta-1-opcion-4-texto-A', TRUE),
(54, 'parte-3-pregunta-1-opcion-4-texto-B', FALSE),
(54, 'parte-3-pregunta-1-opcion-4-texto-C', FALSE),
(55, 'parte-3-pregunta-1-opcion-5-texto-A', TRUE),
(55, 'parte-3-pregunta-1-opcion-5-texto-B', FALSE),
(55, 'parte-3-pregunta-1-opcion-5-texto-C', FALSE),
(56, 'parte-3-pregunta-2-opcion-1-texto-A', TRUE),
(56, 'parte-3-pregunta-2-opcion-1-texto-B', FALSE),
(56, 'parte-3-pregunta-2-opcion-1-texto-C', FALSE),
(57, 'parte-3-pregunta-2-opcion-2-texto-A', TRUE),
(57, 'parte-3-pregunta-2-opcion-2-texto-B', FALSE),
(57, 'parte-3-pregunta-2-opcion-2-texto-C', FALSE),
(58, 'parte-3-pregunta-2-opcion-3-texto-A', TRUE),
(58, 'parte-3-pregunta-2-opcion-3-texto-B', FALSE),
(58, 'parte-3-pregunta-2-opcion-3-texto-C', FALSE),
(59, 'parte-3-pregunta-2-opcion-4-texto-A', TRUE),
(59, 'parte-3-pregunta-2-opcion-4-texto-B', FALSE),
(59, 'parte-3-pregunta-2-opcion-4-texto-C', FALSE),
(60, 'parte-3-pregunta-2-opcion-5-texto-A', TRUE),
(60, 'parte-3-pregunta-2-opcion-5-texto-B', FALSE),
(60, 'parte-3-pregunta-2-opcion-5-texto-C', FALSE),
(61, 'parte-3-pregunta-3-opcion-1-texto-A', TRUE),
(61, 'parte-3-pregunta-3-opcion-1-texto-B', FALSE),
(61, 'parte-3-pregunta-3-opcion-1-texto-C', FALSE),
(62, 'parte-3-pregunta-3-opcion-2-texto-A', TRUE),
(62, 'parte-3-pregunta-3-opcion-2-texto-B', FALSE),
(62, 'parte-3-pregunta-3-opcion-2-texto-C', FALSE),
(63, 'parte-3-pregunta-3-opcion-3-texto-A', TRUE),
(63, 'parte-3-pregunta-3-opcion-3-texto-B', FALSE),
(63, 'parte-3-pregunta-3-opcion-3-texto-C', FALSE),
(64, 'parte-3-pregunta-3-opcion-4-texto-A', TRUE),
(64, 'parte-3-pregunta-3-opcion-4-texto-B', FALSE),
(64, 'parte-3-pregunta-3-opcion-4-texto-C', FALSE),
(65, 'parte-3-pregunta-3-opcion-5-texto-A', TRUE),
(65, 'parte-3-pregunta-3-opcion-5-texto-B', FALSE),
(65, 'parte-3-pregunta-3-opcion-5-texto-C', FALSE);

texto
